<?php
session_start();
if(!($_SESSION["user_id"] && $_SESSION["user_name"]))
header("Location:login.php");


require('fpdf.php');

class PDF extends FPDF
{
// Page header
function Header()
{
    // Logo
    $this->Image('./images/pdf-header.png',20,10,-110,40);
    // Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(60);
    // Title
   // $this->Cell(30,10,'Title',1,0,'C');
    // Line break
    $this->Ln(42); 
}

function ChapterTitle($title,$refNo,$expertName,$collegeName,$yr)
{
    // Arial 12
    $this->SetFont('Arial','',10);
    // Background color
    $this->SetFillColor(200,220,255);
    // Title
    $this->Cell(0,5,'Ref No: E.C.D. (    )    '.$refNo.'  / '.$yr.' '.$title,0,1,'l',true);
    // Line break
   $this->Ln(2);
	$this->Cell(0,8,'  '.$expertName.',',0,1);
	//$this->Ln(2);
	$this->Cell(0,6,'  '.$collegeName.' ',0,1);
	$this->Ln();
	
}


function chapterBody($txt,$pCode,$pName,$pYrSem,$subjName,$qTotal,$signBy,$lbl)
{
   // Read text file
    //$txt = file_get_contents($file);
    // Times 12
    $this->SetFont('Times','BIU',14);
	$this->Cell(0,8,'Subject: Appointed as Question Setting Expert', 0, 0,'C');
	$this->Ln();
	$this->Ln();
	$this->SetFont('Times','',12);
	    // Output justified text
    $this->MultiCell(0,8,$txt,0,'L',False);
    // Line break
	$this->SetFont('Times','B',12);
	$this->Cell(0,10,'Program       : '.$pName);
	$this->Ln();
	$this->Cell(0,10,'Level            : '.$lbl);
	$this->Ln();
	$this->Cell(0,10,'Year/Part    : '.$pYrSem);
	$this->Ln();
	$this->Cell(0,10,'Subject        : '.$subjName);
	$this->Ln();
	$this->Cell(0,10,'Code No      : '.$pCode);
	$this->Ln();
	$this->Cell(0,10,'Total Set(s) : '.$qTotal);
	
	$this->Ln();$this->Ln();
	
	
	$this->SetFont('Times','BI',10);
	$txt1 = '1) Please see backside for question setting guideline. Consult with other experts if there is more experts for this subject ';
	$this->Cell(0,6,$txt1,0,'L',False);
	$txt1='2) Please contact ECD any time if this is not your subject and there is confusion in question setting.';$this->Ln();
	$this->Cell(0,6,$txt1,0,'L',False);$this->Ln();
	$txt1='3) There is a provision to provide CASH on the spot as remuneration by account section of ECD to concerned Expert              as per the ECD rule';
	$this->MultiCell(0,6,$txt1,0,'L',False); 
	$txt1='4) Computer typed question set printed in a secure environment would be highly appreciable.';
	$this->MultiCell(0,6,$txt1,0,'L',False); $this->Ln();	
	$this->SetFont('Times','',12);
	$this->Ln();$this->Ln();
	$this->Cell(0,10,'____________________',0,0,'R');
	$this->Ln();
	$this->Cell(0,8,$signBy,0,0,'R');
	$this->Ln();
	$this->Cell(0,8,'Deputy Chief',0,0,'R');
	// Mention in italics
 
   // $this->Cell(0,5,'(end of excerpt)');
}


// Page footer
function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
	$genDate=date("F j, Y");
    $this->Cell(0,10,'Generated by Software on: '.$genDate,0,0,'C');
}
}


//database connection and data extraction  
$pdf = new PDF();
$pdf->SetLeftMargin(20);
$pdf->AliasNbPages();
//$pdf->AddPage();
$pdf->SetFont('Times','',12);

$refStart = 5;
$refEnd = 10;
    
include("dbconfig.php");
$yr=$_POST['yearName'];
$semType=$_POST['semType'];
$refStart=$_POST['startRef'];
$refEnd=$_POST['endRef'];
$signBy=$_POST['signBy'];
$lbl=$_POST['lbl'];

if(strlen($refStart)<1 or strlen($refEnd)<1 or strlen($signBy)<5)
	{echo '<br/><center><font size="16" color="RED">ERROR: Please Specify all field values</font></center>'; die();}
  $commentBy = 	$yr.'-'.$semType;
$sql='select distinct * from appointQExpert where effYearSem =\''.$commentBy.'\' and label =\''.$lbl.'\' and refNo between '.$refStart.' and '.$refEnd;  //$params = array("%$commentBy%");
  $stmt=$conn->prepare($sql);
  $stmt->execute();

  $mnth=($semType=="bhadra"?"Bhadra":"Chaitra");
  
  $strBody='This is to inform you that to conduct exam of Year: '.$yr.' & Month: '.$mnth.', IOE Examination Control Division has appointed you as a question setting expert. You are requested to prepare the question(s) as per the following details and submit your work to ECD within 7 days from the date of receipt of this letter.';
$title = '                                                                                           Date:  '.date("F j, Y").' ';
$row = $stmt->fetch();
if ($row==NULL)
{echo $sql.'<br/>No record found or mising field values. Please specify field values correctly'; die();}

do 
	{
		$refNo = $row{'refNo'};
		//$exprID = $row{'expertID'};
		$exprName = $row{'expertName'};
		$pCode = $row{'pCode'};
		$pName = $row{'pName'};
		$pYrSem = $row{'pYrSem'};
		$subjName = $row{'subjName'};
		$collegeName = $row{'collegeName'};
		$qTotal = $row{'qTotal'};
	//	$label= $row{'label'};
		//$effYearSem = $row{'effYearSem'};
	
	
	$pdf->AddPage();
    $pdf->ChapterTitle($title,$refNo,$exprName,getCollegeAddress($collegeName),$yr);
    $pdf->ChapterBody($strBody,$pCode,$pName,$pYrSem,$subjName,$qTotal,$signBy, $lbl);	
	} while ($row = $stmt->fetch());
	
 // Instanciation of inherited class 

function getCollegeAddress($collegeCode)
{
switch($collegeCode)
{
case "PUL": $addr = "Pulchowk Engineering Campus"; break;
case "THA": $addr= "Thapathali Engineering Campus"; break;
case "PAS": $addr= "Paschimanchal Engineering Campus"; break;
case "PUR": $addr= "Purwanchal Engineering Campus"; break;
case "KAT": $addr= "Kathmandu Engineering College"; break;
case "KAN": $addr= "Kantipur Engineering College"; break;
case "ACE": $addr= "Advance College of Eng. & Mgmt."; break;
case "SEC": $addr= "Sagarmatha Engineering College"; break;
case "LEC": $addr= "Lalitpur Engineering College"; break;
case "NCE": $addr= "National College of Engineering"; break;
case "HCE": $addr= "Himalaya College of Engineering"; break;
case "KIC": $addr= "Kathford Intl College of Engg. & Mgmt. "; break;
case "KCE": $addr= "Khowpa College of Engineering"; break;
case "JEC": $addr= "Janakpur Engineering College"; break;
default: $addr = $collegeCode;
}
return $addr;
}

   
//$pdf->PrintChapter('',$title,$strBody);
$conn=null;

$dir="d:\\qset\\";
$fileName = $yr.'-'.$semType.'-'.$refStart.'-'.$refEnd.'.pdf';
$pdf->Output();
//echo 'PDF file generated sucessfully';
?>